version: '3'

services:
  service-a:
    build: .
    restart: always
    container_name: rest-client
    command: python -m app.rest
    environment:
     - RABBIT_MQ_URL=amqp://guest:guest@rabbitmq/
    ports:
      - "8080:8080"
    depends_on:
      - service-b
    networks:
      - microservices

  service-b:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - microservices

  service-c:
    build: .
    restart: always
    container_name: rpc-server
    command: python -m app.rpc_server
    environment:
     - RABBIT_MQ_URL=amqp://guest:guest@rabbitmq/
    depends_on:
      - service-b
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
